name: Deploy to wm-selector.github.io
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: wm-selector/wm-selector.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: wm-selector.github.io
      - uses: actions/setup-node@v3
      - name: Build and Deploy
        run: |
          npm ci
          npm run build
          rm -Rf wm-selector.github.io/*
          cp -Rf dist/* wm-selector.github.io/
          cd wm-selector.github.io/
          git config user.email 'MattBlissett@users.noreply.github.com'
          git config user.name 'Matt Blissett'
          git checkout README.md
          git add .
          git commit -m '${{ github.repository }} ${{ github.sha }}'
          git push -f origin main
